### PR TITLE
[cleanup-list] Added cleanup-list script

### PR DESCRIPTION
**Pull request by Foxboron**
Aids packagers figuring out orphans required by packages and unneeded
orphans.

Signed-off-by: Morten Linderud <morten@linderud.pw>

### CODE REVIEW

**Comment by jelly** [comment]
@Foxboron how different is it from https://www.archlinux.org/devel/reports/unneeded-orphans/

**Comment by Foxboron** [comment]
@jelly That only lists the unneeded ones. This ones finds orphans and the dependant packages with the maintainer - suggesting maintainers essentially.

**Comment by Foxboron** [comment]
See: https://lists.archlinux.org/pipermail/arch-dev-public/2017-December/029052.html

**Comment by jelly** [comment]
I see, yeah we still want that in archweb (suggested maintainers)

**Pull request merged**
