### PR TITLE
Add tool to generate dbscripts commands for todolists

### PR DESCRIPTION
**Pull request by jelly**
staging2testing outputs the to be executed commands for a todolist which
can be moved to [testing].

Signed-off-by: Jelle van der Waa <jelle@archlinux.org>

### CODE REVIEW

**Comment by Foxboron** [comment]
Is this missing the `staging2testing` tool itself?

**Comment by jelly** [comment]
lies!

**Comment by Foxboron** [comment]
Missing an SPDX license header then this is fine to merge :)

**Comment by jelly** [comment]
It also needs to handle testing => extra ideally ;-)

**Comment by jelly** [comment]
So just add an extra argument ideally, target? testing or stable!

**Pull request merged**
