### PR TITLE
Add diffpypi

### PR DESCRIPTION
**Pull request by felixonmars**
Simple tool to compare metadata file for PyPI projects. This can ease
maintenance of Python libraries/projects just like diffcabal, by
downloading and comparing for metadata changes so they are not
overlooked which resulting in broken packages.

### CODE REVIEW

**Comment by anthraxx** [comment]
This script is full of static locations in a world writable directory aka /tmp which is both, not race condition free nor secure.
Please stop using static locations in /tmp

**Comment by felixonmars** [comment]
@anthraxx It's using a static location to avoid re-downloading the same source files to compare each time. It's also put into /tmp because I don't want to keep those files between reboots.

**Comment by anthraxx** [comment]
That's not a good idea and has the same fundamental underlying issues as the haskell static files had. It's should be avoided to use patterns like this.
An alternative idea would be to simply use everything in a mktemp directory or use XDG cache locations and cleanup after processing.
At this point in wondering why we not just use curl piped to tar and use a file handle via <() and avoid having any Filesystem access

**Comment by anthraxx** [comment]
Or to rephrase it slightly.

I believe we try to fix a nearly non issue in a way that introduces multiple issues on its own. Not cleaning up dirt in/tmp is not a good poor man's cache, it consumes your memory (tmpfs) for no good reason and one would be forced to investigate where all the space went and manually delete stuff -- or reboot.

You rarely want to call the same versions as often as redownloading would make a difference nor do you want to reboot nearly never so multiple new versions will be available as old versions for the next diff... That in the meanwhile would clutter tons of things in /tmp

My call is to remove this caching logic all together, or consider redownloading a primary issue and implement something more sophisticated to mitigate the shortcomings introduced by using /tmp as a semi persistent tarball cache.

**Comment by felixonmars** [comment]
The typical usage here is to compare setup.py first (default behavior) and one can choose to continue comparing other files, which happens quite often since Python has different metadata schemas all over the place. Disabling caching altogether would render this tool rather useless because it's way bigger than a simple cabal file so downloading is the most time consuming part already.

**Comment by anthraxx** [comment]
Okay, then out it in XDG cache dir and come up with some auto cleanup logic or such.
Tmp is really not the solution for this kind of problems, also if it is such a major concern then it should also be reboot safe. But whatever is done please do not use static locations in /tmp

**Pull request merged**
