### PR TITLE
copy remote files to PKGDEST on initiating machine

### PR DESCRIPTION
**Pull request by kgizdov**
#2

### CODE REVIEW

**Comment by Foxboron** [comment]
Missing quotes around variables.

**Comment by kgizdov** [comment]
I think now that's pretty minimal and should work without issue.

**Comment by eli-schwartz** [comment]
I don't think I've ever seen a thirdparty makepkg wrapper that successfully parsed makepkg.conf and I specifically don't want to do so if it is going to be done wrongly.

This one fails to correctly handle environment variables, then uses the wrong user config file precedence and totally ignores the system config file.

I have long-term plans to have makepkg export a proper config parser and I greatly dislike the idea of adding yet more code that has large edge cases and will need to be replaced anyway.

**Comment by eli-schwartz** [comment]
> I think now that's pretty minimal and should work without issue.

I did not notice this new attempt. Looking at it, it now sets PKGDEST=/path/to/foo.pkg.tar.xz which is pretty problematic.

**Comment by kgizdov** [comment]
@eli-schwartz no, it doesn't

**Comment by eli-schwartz** [comment]
```
$ dirname "$(makepkg --packagelist)" | xargs | cut -d" " -f1
/var/cache/pacman/custom/glibc-git-2.29.r197.ge3f454bac0-1-x86_64.pkg.tar.xz
```

**Comment by kgizdov** [comment]
@eli-schwartz the quotes are gone, miscommit

**Comment by kgizdov** [comment]
> I have long-term plans to have makepkg export a proper config parser and I greatly dislike the idea of adding yet more code that has large edge cases and will need to be replaced anyway.

That'd be cool indeed. But for now, I think that's adequate, since it's still using `makepkg`.

**Comment by svenstaro** [comment]
What's the status on this? @eli-schwartz, you don't like this change at all because you don't think it can be solidly implemented right now?

**Comment by eli-schwartz** [comment]
The current status is that I submitted https://lists.archlinux.org/pipermail/pacman-dev/2019-April/023341.html in order to expose the makepkg.conf as an official part of the makepkg API, and would like to use that in this and other scripts. Allan said he would be back to do some more patch review on Monday, so I'm hoping that patch will be accepted then. At that point, we'd still need to decide on a release schedule for pacman 5.2  before `load_makepkg_config` would be available, but it would be usable in pacman-git.

The advantage of this libmakepkg drop-in over the current "parsing makepkg --packagelist" method would be not needing to re-run the makepkg setup stuff (and do slow lint checks), which granted is not the main timewaster when building chromium or tensorflow :p.
My slightly bash-obsessive nitpicky tendencies :D consider the libmakepkg route a more elegant solution.

If I had to implement it today (I don't personally use PKGDEST in situations where I'd want to use offload-build) I would probably just source makepkg.conf myself, though. The precedence for doing so is simple enough and documented, if verbose. Inlining the config.sh which I submitted to pacman-dev would do the trick, for one.

**Comment by jelly** [comment]
offload-build has now been moved to devtools.

**Pull request closed without merging**
